//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Repairs = new HashSet<Repair>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int CustomerID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int AddressID { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Repair> Repairs { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
