//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSale
    {
        public int CustomerID { get; set; }
        public int AddressID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TelNumber { get; set; }
        public string FirstLine { get; set; }
        public string SecondLine { get; set; }
        public string Town { get; set; }
        public string PostCode { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string ItemName { get; set; }
        public string FrameNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Comments { get; set; }
    }
}
