//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ItemName { get; set; }
        public string FrameNo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
