'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Address
    Public Property AddressID As Integer
    Public Property FirstLine As String
    Public Property Town As String
    Public Property PostCode As String
    Public Property Comments As String
    Public Property Telephone As Integer
    Public Property Mobile As Integer
    Public Property Email As Nullable(Of Integer)

    Public Overridable Property Customers As ICollection(Of Customer) = New HashSet(Of Customer)

End Class
