'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BicycleToCustomersMapping
    Public Property MappingID As Integer
    Public Property BicycleID As Nullable(Of Integer)
    Public Property CustomerID As Nullable(Of Integer)

    Public Overridable Property Bicycle As Bicycle
    Public Overridable Property Customer As Customer

End Class
