'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bicycle
    Public Property BicycleID As Integer
    Public Property TypeID As Nullable(Of Integer)
    Public Property Make As String
    Public Property DateMake As Nullable(Of Date)
    Public Property Comments As String

    Public Overridable Property BicycleType As BicycleType
    Public Overridable Property BicycleToCustomersMappings As ICollection(Of BicycleToCustomersMapping) = New HashSet(Of BicycleToCustomersMapping)
    Public Overridable Property Repairs As ICollection(Of Repair) = New HashSet(Of Repair)

End Class
