'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CustomerRepair
    Public Property FirstName As String
    Public Property LastName As String
    Public Property Telephone As Integer
    Public Property Mobile As Integer
    Public Property Make As String
    Public Property DateMake As Nullable(Of Date)
    Public Property BikeDetails As String
    Public Property OrderDate As Nullable(Of Date)
    Public Property DueDate As Nullable(Of Date)
    Public Property Price As Nullable(Of Decimal)
    Public Property RepairDetails As String

End Class
